apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-deployment
  labels:
    app: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app 
    spec:
      containers:
      - name: nodeserver
        image: adamrs25/pingpong-app:latest
        ports:
        - containerPort: 3000